# This is a basic workflow to help you get started with Actions

name: install tau

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: setup prequisites
        run: |
          sudo apt-get install socat

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.61.1
        with:
          ruby-version: 2.7

      - name: install tau
        run: gem install takelage

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: pull takelage image
        run: tau update -l debug

      - name: try tau login
        shell: 'script -q -e -c "bash {0}"'
        run: |
          tau login
          ps -ef

      # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #   shell: 'script -q -e -c "bash {0}"'
      #   run: |
      #     perl -E 'say "Is STDOUT a TTY?: ", -t STDOUT ? "yes" : "no"'
      #     docker network create takelage_and_action
      #     docker run --detach -t \
      #       --env TAKELAGE_PROJECT_BASE_DIR=/home/runner/work/and_action/and_action \
      #       --env TZ=Europe/Berlin \
      #       --hostname takelage_and_action --name takelage_and_action --network takelage_and_action \
      #       --privileged --rm --shm-size 512M \
      #       --volume /var/run/docker.sock:/var/run/docker.sock \
      #       --volume /home/runner:/hostdir \
      #       --volume $GITHUB_WORKSPACE:/project --workdir /project \
      #       --add-host host.docker.internal:172.17.0.1 \
      #       --env GOOGLE_APPLICATION_CREDENTIALS=/hostdir/.google/default.json \
      #       takelage/takelage:latest /entrypoint.py --gid 116 --home /home/runner --uid 1001 --username runner --gpg_agent_port 17874 --gpg_ssh_agent_port 17875 --extra=.config/gcloud

      - name: check things
        run: |
          printenv
          docker exec -i takelage_and_action pwd
          docker exec -i takelage_and_action ls -ls
          docker exec -i takelage_and_action ps -ef
